### ISSUE TITLE
Use Honcho

### ISSUE THREAD

**Issue by JolieKimy** [HE-Arc/Synai#5]
@greut recomand to use Honcho instead of the makefile.

 https://pypi.org/project/honcho/

**Comment by greut** [comment]
especially for such a simple case. But I'm biased

**Comment by Naralas** [comment]
Actually we have a workshop planned next Thursday for automated deployment. We are going to use Capistrano instead.

**Comment by greut** [comment]
@Naralas that's pretty useful for a local usage.

**Comment by greut** [comment]
e.g.
```
web: python manage.py runserver
mysql: docker run --rm -v $PWD/mysqldata:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw -p 3306:3306 mysql:8
```
